version: '3'
services:
  consumer:
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  producer:
    build:
      context: ./Producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
